name: Deploy to GitHub Pages

on:
  push:
    branches: ['main', 'master']
    paths:
      - 'token-studio/**'
      - '.github/workflows/**'
      - 'src/**'
      - '**/*.js'
      - '**/*.ts'
      - '**/*.vue'
      - '**/*.html'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Need at least 2 commits for diff checking
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          npm install
          # Explicitly install vue-router if needed
          npm list vue-router || npm install vue-router@4
        
      - name: Check for token-studio changes
        id: check_changes
        run: |
          git diff --quiet HEAD^ HEAD -- token-studio/ || echo "token_changes=true" >> $GITHUB_OUTPUT
        continue-on-error: true
        
      - name: Check token-studio structure
        if: steps.check_changes.outputs.token_changes == 'true'
        run: |
          ls -la token-studio/
          if [ -f "token-studio/tokens.json" ]; then
            echo "tokens.json exists!"
          else
            echo "Warning: tokens.json not found in token-studio directory"
          fi
        
      - name: Run token splitter if tokens changed
        if: steps.check_changes.outputs.token_changes == 'true'
        run: |
          mkdir -p token-studio/tokens/brands
          mkdir -p token-studio/tokens/color
          mkdir -p token-studio/tokens/font
          mkdir -p token-studio/tokens/scale
          mkdir -p token-studio/src/styles/tokens
          python token-studio/split_tokens.py
        
      - name: Check token directory structure after split
        if: steps.check_changes.outputs.token_changes == 'true'
        run: |
          echo "Directory structure after token split:"
          find token-studio -type d | sort
          echo "Generated SCSS files:"
          find token-studio -name "*.scss" | sort
        
      - name: Run token organizer after split
        if: steps.check_changes.outputs.token_changes == 'true'
        run: |
          # Add PYTHONPATH to include the repository root
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python token-studio/src/styles/organize_tokens.py
        
      # Creating a temporary vite.config.js to properly handle dependencies
      - name: Configure Vite
        run: |
          if [ -f "vite.config.js" ]; then
            # Backup original config
            cp vite.config.js vite.config.js.backup
            # Add vue-router to external if it doesn't exist
            grep -q "vue-router" vite.config.js || sed -i '/build: {/a \    rollupOptions: { external: ["vue-router"] },' vite.config.js
          else
            echo "Creating basic vite.config.js"
            echo 'import { defineConfig } from "vite";
            export default defineConfig({
              build: {
                rollupOptions: {
                  external: ["vue-router"]
                }
              }
            });' > vite.config.js
          fi
          cat vite.config.js
        
      - name: Build for GitHub Pages
        run: npm run build
        
      - name: Restore original Vite config if needed
        run: |
          if [ -f "vite.config.js.backup" ]; then
            mv vite.config.js.backup vite.config.js
          fi
        continue-on-error: true
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 